### ISSUE TITLE
Javascript error when clicking to full results

### ISSUE THREAD

**Issue by galbaras** [Kuroit/Advanced-Admin-Search#1]
After running a search, there is a list of up to 8 results, followed by what seems to be a link to all of the results. However, when this link is clicked, the browser console shows `Uncaught SyntaxError: Invalid or unexpected token` for the current page, e.g. `plugins.php`.

Clicking the link on the page name opens up a page containing `javascript:alert(\`, so something is really missing there.

**Comment by galbaras** [comment]
Rather than link to a page with all the results, the plugin can include a "next/prev" navigation to get the next/previous lot of 10 results. This is likely easier to implement using existing functions.

**Comment by puneetkay** [comment]
Issue fixed with the release, thanks for pointing out!
