### ISSUE TITLE
Vulnerability issue?

### ISSUE THREAD

**Issue by macbaydigital** [Kuroit/Advanced-Admin-Search#10]
Hi,

some time ago, I have installed this plugin from [wp.org](https://wordpress.org/plugins/advanced-admin-search/) and it's really useful! Thank you for providing this plugin 🙏

But it's not available any more:

"This plugin has been closed as of April 26, 2022 and is not available for download. This closure is temporary, pending a full review."

I did some research and came across a [vulnerability report](https://wpguynews.com/wordpress-vulnerability-report-may-25-2022/) from May 2022, where an issue is stated regarding cross-site scripting.

I have also seen here, that some CSS files of this plugin have been updated.

So my question is, if you're bringing back this plugin to wp.org, so we can update using default-update-procedure via the wp-dashboard?

Thank you in advance and kind regards,
Sascha

**Comment by puneetkay** [comment]
Hello @sushinger 

Thank you for your feedback!

Vulnerability issue has been fixed and code has been pushed to WP SVN.
It is currently under review by WP team for some minor changes, we're working closely with WP team to get the plugin back online as soon as possible.

I will also push the latest code here shortly.

Thanks,
Puneet

**Comment by puneetkay** [comment]
Hello again,

I have pushed the latest code here on Github as well as WP SVN.
Still waiting to hear from WP team, you can download and use the code from here in the meantime.

Thanks
