### ISSUE TITLE
Limiting search to published items only

### ISSUE THREAD

**Issue by galbaras** [Kuroit/Advanced-Admin-Search#3]
On some of my sites, I get results appearing in drafts or pending content, and I’d love to have a way to narrow the search down by content status.

While we're at it, it'll be great to have other selections, such as content types, range of dates, etc.

**Comment by galbaras** [comment]
Any thoughts?

**Comment by puneetkay** [comment]
Sorry for taking way too long to reply here.

This feature is already made available on the dedicated Advanced Admin Search page under Tools menu.
